# Generated by Django 5.0.6 on 2024-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=300)),
                ('Field_id', models.IntegerField()),
                ('Table_id', models.IntegerField()),
                ('Order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('date_field', 'Date Field')], max_length=20)),
                ('Table_id', models.IntegerField()),
                ('Order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
