# Generated by Django 5.0.6 on 2024-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Fields',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
