# Generated by Django 5.0.6 on 2024-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_table_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='Type',
            field=models.CharField(max_length=20),
        ),
    ]
