# Generated by Django 5.0.6 on 2024-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
